apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiperdev-api-balves
  namespace: hiperdev
spec:
  selector:
    matchLabels:
      app: hiperdev-api-balves
  template:
    metadata:
      labels:
        app: hiperdev-api-balves
    spec:
      containers:
      - name: hiperdev-api-balves
        image: hiperdevcr.azurecr.io/hiperdev
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
